api_platform:
    title: forumify API
    version: 1.0.0
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    use_symfony_listeners: true
    enable_link_security: true
    eager_loading:
        force_eager: false
    defaults:
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        pagination_enabled: true
        page_parameter_name: '_page'
        pagination_client_enabled: false
        pagination_client_items_per_page: true
        pagination_items_per_page: 25
        pagination_maximum_items_per_page: 1000
        items_per_page_parameter_name: '_limit'
    formats:
        jsonld: [ 'application/ld+json', 'application/json' ]
        multipart: [ 'multipart/form-data' ]
    patch_formats:
        jsonld: [ 'application/merge-patch+json', 'application/json' ]
    mapping:
        paths:
            - '%kernel.project_dir%/src/'
            - '%forumify.project_dir%/src/'
