doctrine:
    orm:
        mappings:
            forumify_core:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src/Core/Entity'
                prefix: Forumify\Core\Entity
                alias: ForumifyCore
            forumify_forum:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src/Forum/Entity'
                prefix: Forumify\Forum\Entity
                alias: ForumifyForum
            forumify_cms:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src/Cms/Entity'
                prefix: Forumify\Cms\Entity
                alias: ForumifyCms
            forumify_plugin:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src/Plugin/Entity'
                prefix: Forumify\Plugin\Entity
                alias: ForumifyPlugin
