doctrine:
    orm:
        mappings:
            forumify:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src'
                prefix: Forumify
                alias: Forumify
