doctrine:
    orm:
        enable_native_lazy_objects: true
        mappings:
            forumify:
                is_bundle: false
                type: attribute
                dir: '%forumify.project_dir%/src'
                prefix: Forumify
                alias: Forumify
