doctrine_migrations:
    migrations_paths:
        'ForumifyDoctrineMigrations': '%forumify.project_dir%/migrations'

    services:
        'Doctrine\Migrations\Version\Comparator': 'Forumify\Core\Service\DoctrineVersionComparator'
