framework:
    assets:
        packages:
            forumify.avatar:
                base_path: '%forumify.avatar.storage.path%'
            forumify.asset:
                base_path: '%forumify.asset.storage.path%'
            forumify.resource:
                base_path: '%forumify.resource.storage.path%'
            forumify.media:
                base_path: '%forumify.media.storage.path%'
    router:
        default_uri: '%env(DEFAULT_URI)%'
    session:
        name: '%env(hostname:DEFAULT_URI)%-sessid'
