framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'Forumify\Core\Messenger\AsyncMessageInterface': async

when@dev:
    framework:
        messenger:
            transports:
                async: 'in-memory://'

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
