admin:
    resource: ../../src/Admin/Controller
    type: attribute
    name_prefix: admin_
    prefix: admin/

api:
    resource: ../../src/Api/Controller
    type: attribute
    name_prefix: api_
    prefix: api/

api_platform:
    resource: .
    type: api_platform
    prefix: /api

core:
    resource: ../../src/Core/Controller
    type: attribute
    name_prefix: core_

forum:
    resource: ../../src/Forum/Controller
    type: attribute
    name_prefix: forum_

page:
    resource: ../../src/Cms/Controller/Frontend
    type: attribute
    name_prefix: cms_

page_admin:
    resource: ../../src/Cms/Controller/Admin
    type: attribute
    name_prefix: admin_cms_
    prefix: admin/cms/
