core:
    resource: ../../src/Core/Controller
    type: attribute
    name_prefix: core_

admin:
    resource: ../../src/Admin/Controller
    type: attribute
    name_prefix: admin_
    prefix: admin/

forum:
    resource: ../../src/Forum/Controller
    type: attribute
    name_prefix: forum_

oauth:
    resource: ../../src/OAuth/Controller
    type: attribute
    name_prefix: oauth_
    prefix: oauth

page:
    resource: ../../src/Cms/Controller/Frontend
    type: attribute
    name_prefix: cms_

page_admin:
    resource: ../../src/Cms/Controller/Admin
    type: attribute
    name_prefix: admin_cms_
    prefix: admin/cms/
