forumify:
    resource: routes/forumify.yaml
    name_prefix: forumify_

plugin_routes:
    resource: .
    type: forumify_plugin

api_platform:
    resource: .
    type: api_platform
    prefix: /api
