services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appSecret: '%env(APP_SECRET)%'

    Forumify\:
        resource: '../src/'
        exclude:
            - '../src/**/DataFixture/'
            - '../src/**/DependencyInjection/'
            - '../src/**/Entity/'
