services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appSecret: '%env(APP_SECRET)%'

    Forumify\:
        resource: '../src/'
        exclude:
            - '../src/**/DataFixture/*'
            - '../src/**/DependencyInjection/*'
            - '../src/**/Entity/*'
            - '../src/Plugin/Application/*'
            - '../src/Core/ForumifyKernel.php'

    cache.adapter.forumify:
        class: Symfony\Component\Cache\Adapter\FilesystemTagAwareAdapter
        parent: cache.adapter.filesystem
