name: Code Quality
on:
  pull_request:

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Setup JS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install

      - name: Run PHP checks
        run: |
          ./vendor/bin/phpcs -s --standard=phpcs.xml
          ./vendor/bin/phpstan analyze -v

      - name: Run JS checks
        run: |
          cd assets
          npm install --force
          npm run lint
